#167733642 Build out REST Endpoint for signup
andela/jubilee-backend pull request #21
Opened 2019-08-22 17:25 UTC by King-Success

### What does this PR do?
Have user registration endpoint with token generation on successful signup
### Description of Task to be completed?
- Install dependencies
- Verify app connects to the database
- Create a User model
- Create a corresponding User migration file
- Set up scripts for running migration commands
- Refactor app to use JWT instead of session
- Create a User service that interface with the database
- Create a User controller that saves the user in the database
- Create signup route
- Write the test for signup route

### How should this be manually tested?
- Clone this repository
- Copy environment variable sample from .env.sample into .env and fill in the required variables
- On the root directory, run docker-compose up -d to start up both app and a database instance on docker
- Alternatively, run npm start-dev on project root directory to bypass docker. but ensure to provide the right database connections
- Run npm run migrate to run migration file. Check your database for a newly added Users table
- Run npm run migrate:reset to drop said Users table
- On Postman, call `POST /api/auth/signup` with
```
{
    firstName: string,
    lastName: string,
    email: string,
    gender: string,
    street: string;
    city: string,
    state: string,
    country: string,
    bithdate: Date,
    phoneNumber: string,
    companyName: string
}
```
### Any background context you want to provide?
As mentioned above, this feature can be tested with or without docker. This is also a prerequisite for a lot of other features hence it needs to be reviewed in order to unblock team members
### What are the relevant pivotal tracker stories?
[#167733642](https://www.pivotaltracker.com/story/show/167733642)

2019-08-22 18:57 UTC, chis0m commented on .gitignore
> -# End of https://www.gitignore.io/api/node
requires a new line feed

2019-08-22 19:08 UTC, chis0m approved these changes

2019-08-22 19:10 UTC, chis0m reviewed
Nice job

2019-08-22 19:18 UTC, Baystef commented on src/index.js
>  app.use(bodyParser.json());
This could actually be `app.use(express.json)` so we can do away with the redundant body-parser

2019-08-22 19:21 UTC, Baystef commented on src/config/config.js
> +// import dotenv from 'dotenv';
Kindly remove the commented out code

2019-08-22 19:24 UTC, Baystef approved these changes
No major issues sighted so PR is good to go

2019-08-22 23:42 UTC, emmanuelnwankwo requested changes

2019-08-22 23:42 UTC, emmanuelnwankwo commented on src/models/index.js
> +// import dotenv from 'dotenv';
Uncomment this line and consider removing _const dotenv = require('dotenv');_

2019-08-23 08:17 UTC, emmanuelnwankwo approved these changes

2019-08-23 12:59 UTC, merged